name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'images/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/chiaracarrino/olma-ollama-money-analysis

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4


      - name: Login a GHCR
        uses: docker/login-action@v3

        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push immagine
        uses: docker/build-push-action@v5

        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v2.0.0
